// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	types "splitnow/internal/types"

	mock "github.com/stretchr/testify/mock"
)

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

type Store_Expecter struct {
	mock *mock.Mock
}

func (_m *Store) EXPECT() *Store_Expecter {
	return &Store_Expecter{mock: &_m.Mock}
}

// AddMember provides a mock function with given fields: userID, roomID
func (_m *Store) AddMember(userID int, roomID int) (types.Membership, error) {
	ret := _m.Called(userID, roomID)

	if len(ret) == 0 {
		panic("no return value specified for AddMember")
	}

	var r0 types.Membership
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int) (types.Membership, error)); ok {
		return rf(userID, roomID)
	}
	if rf, ok := ret.Get(0).(func(int, int) types.Membership); ok {
		r0 = rf(userID, roomID)
	} else {
		r0 = ret.Get(0).(types.Membership)
	}

	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(userID, roomID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_AddMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddMember'
type Store_AddMember_Call struct {
	*mock.Call
}

// AddMember is a helper method to define mock.On call
//   - userID int
//   - roomID int
func (_e *Store_Expecter) AddMember(userID interface{}, roomID interface{}) *Store_AddMember_Call {
	return &Store_AddMember_Call{Call: _e.mock.On("AddMember", userID, roomID)}
}

func (_c *Store_AddMember_Call) Run(run func(userID int, roomID int)) *Store_AddMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int))
	})
	return _c
}

func (_c *Store_AddMember_Call) Return(_a0 types.Membership, _a1 error) *Store_AddMember_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_AddMember_Call) RunAndReturn(run func(int, int) (types.Membership, error)) *Store_AddMember_Call {
	_c.Call.Return(run)
	return _c
}

// CreateMessage provides a mock function with given fields: roomID, sender, content
func (_m *Store) CreateMessage(roomID int, sender string, content string) (types.Message, error) {
	ret := _m.Called(roomID, sender, content)

	if len(ret) == 0 {
		panic("no return value specified for CreateMessage")
	}

	var r0 types.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(int, string, string) (types.Message, error)); ok {
		return rf(roomID, sender, content)
	}
	if rf, ok := ret.Get(0).(func(int, string, string) types.Message); ok {
		r0 = rf(roomID, sender, content)
	} else {
		r0 = ret.Get(0).(types.Message)
	}

	if rf, ok := ret.Get(1).(func(int, string, string) error); ok {
		r1 = rf(roomID, sender, content)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_CreateMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMessage'
type Store_CreateMessage_Call struct {
	*mock.Call
}

// CreateMessage is a helper method to define mock.On call
//   - roomID int
//   - sender string
//   - content string
func (_e *Store_Expecter) CreateMessage(roomID interface{}, sender interface{}, content interface{}) *Store_CreateMessage_Call {
	return &Store_CreateMessage_Call{Call: _e.mock.On("CreateMessage", roomID, sender, content)}
}

func (_c *Store_CreateMessage_Call) Run(run func(roomID int, sender string, content string)) *Store_CreateMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Store_CreateMessage_Call) Return(_a0 types.Message, _a1 error) *Store_CreateMessage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_CreateMessage_Call) RunAndReturn(run func(int, string, string) (types.Message, error)) *Store_CreateMessage_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRoom provides a mock function with given fields: name, creator
func (_m *Store) CreateRoom(name string, creator int) (types.Room, error) {
	ret := _m.Called(name, creator)

	if len(ret) == 0 {
		panic("no return value specified for CreateRoom")
	}

	var r0 types.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int) (types.Room, error)); ok {
		return rf(name, creator)
	}
	if rf, ok := ret.Get(0).(func(string, int) types.Room); ok {
		r0 = rf(name, creator)
	} else {
		r0 = ret.Get(0).(types.Room)
	}

	if rf, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = rf(name, creator)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_CreateRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRoom'
type Store_CreateRoom_Call struct {
	*mock.Call
}

// CreateRoom is a helper method to define mock.On call
//   - name string
//   - creator int
func (_e *Store_Expecter) CreateRoom(name interface{}, creator interface{}) *Store_CreateRoom_Call {
	return &Store_CreateRoom_Call{Call: _e.mock.On("CreateRoom", name, creator)}
}

func (_c *Store_CreateRoom_Call) Run(run func(name string, creator int)) *Store_CreateRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int))
	})
	return _c
}

func (_c *Store_CreateRoom_Call) Return(_a0 types.Room, _a1 error) *Store_CreateRoom_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_CreateRoom_Call) RunAndReturn(run func(string, int) (types.Room, error)) *Store_CreateRoom_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllRooms provides a mock function with no fields
func (_m *Store) GetAllRooms() ([]types.Room, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllRooms")
	}

	var r0 []types.Room
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]types.Room, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []types.Room); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Room)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_GetAllRooms_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllRooms'
type Store_GetAllRooms_Call struct {
	*mock.Call
}

// GetAllRooms is a helper method to define mock.On call
func (_e *Store_Expecter) GetAllRooms() *Store_GetAllRooms_Call {
	return &Store_GetAllRooms_Call{Call: _e.mock.On("GetAllRooms")}
}

func (_c *Store_GetAllRooms_Call) Run(run func()) *Store_GetAllRooms_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Store_GetAllRooms_Call) Return(_a0 []types.Room, _a1 error) *Store_GetAllRooms_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_GetAllRooms_Call) RunAndReturn(run func() ([]types.Room, error)) *Store_GetAllRooms_Call {
	_c.Call.Return(run)
	return _c
}

// GetMessagesByRoom provides a mock function with given fields: roomID
func (_m *Store) GetMessagesByRoom(roomID int) ([]types.Message, error) {
	ret := _m.Called(roomID)

	if len(ret) == 0 {
		panic("no return value specified for GetMessagesByRoom")
	}

	var r0 []types.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]types.Message, error)); ok {
		return rf(roomID)
	}
	if rf, ok := ret.Get(0).(func(int) []types.Message); ok {
		r0 = rf(roomID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(roomID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_GetMessagesByRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMessagesByRoom'
type Store_GetMessagesByRoom_Call struct {
	*mock.Call
}

// GetMessagesByRoom is a helper method to define mock.On call
//   - roomID int
func (_e *Store_Expecter) GetMessagesByRoom(roomID interface{}) *Store_GetMessagesByRoom_Call {
	return &Store_GetMessagesByRoom_Call{Call: _e.mock.On("GetMessagesByRoom", roomID)}
}

func (_c *Store_GetMessagesByRoom_Call) Run(run func(roomID int)) *Store_GetMessagesByRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *Store_GetMessagesByRoom_Call) Return(_a0 []types.Message, _a1 error) *Store_GetMessagesByRoom_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_GetMessagesByRoom_Call) RunAndReturn(run func(int) ([]types.Message, error)) *Store_GetMessagesByRoom_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoomsWithName provides a mock function with given fields: name
func (_m *Store) GetRoomsWithName(name string) ([]types.Room, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetRoomsWithName")
	}

	var r0 []types.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]types.Room, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) []types.Room); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_GetRoomsWithName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoomsWithName'
type Store_GetRoomsWithName_Call struct {
	*mock.Call
}

// GetRoomsWithName is a helper method to define mock.On call
//   - name string
func (_e *Store_Expecter) GetRoomsWithName(name interface{}) *Store_GetRoomsWithName_Call {
	return &Store_GetRoomsWithName_Call{Call: _e.mock.On("GetRoomsWithName", name)}
}

func (_c *Store_GetRoomsWithName_Call) Run(run func(name string)) *Store_GetRoomsWithName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Store_GetRoomsWithName_Call) Return(_a0 []types.Room, _a1 error) *Store_GetRoomsWithName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_GetRoomsWithName_Call) RunAndReturn(run func(string) ([]types.Room, error)) *Store_GetRoomsWithName_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserRooms provides a mock function with given fields: userID
func (_m *Store) GetUserRooms(userID int) ([]types.Room, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserRooms")
	}

	var r0 []types.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]types.Room, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(int) []types.Room); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_GetUserRooms_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserRooms'
type Store_GetUserRooms_Call struct {
	*mock.Call
}

// GetUserRooms is a helper method to define mock.On call
//   - userID int
func (_e *Store_Expecter) GetUserRooms(userID interface{}) *Store_GetUserRooms_Call {
	return &Store_GetUserRooms_Call{Call: _e.mock.On("GetUserRooms", userID)}
}

func (_c *Store_GetUserRooms_Call) Run(run func(userID int)) *Store_GetUserRooms_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *Store_GetUserRooms_Call) Return(_a0 []types.Room, _a1 error) *Store_GetUserRooms_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_GetUserRooms_Call) RunAndReturn(run func(int) ([]types.Room, error)) *Store_GetUserRooms_Call {
	_c.Call.Return(run)
	return _c
}

// IsMember provides a mock function with given fields: userID, roomID
func (_m *Store) IsMember(userID int, roomID int) (bool, error) {
	ret := _m.Called(userID, roomID)

	if len(ret) == 0 {
		panic("no return value specified for IsMember")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int) (bool, error)); ok {
		return rf(userID, roomID)
	}
	if rf, ok := ret.Get(0).(func(int, int) bool); ok {
		r0 = rf(userID, roomID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(userID, roomID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_IsMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsMember'
type Store_IsMember_Call struct {
	*mock.Call
}

// IsMember is a helper method to define mock.On call
//   - userID int
//   - roomID int
func (_e *Store_Expecter) IsMember(userID interface{}, roomID interface{}) *Store_IsMember_Call {
	return &Store_IsMember_Call{Call: _e.mock.On("IsMember", userID, roomID)}
}

func (_c *Store_IsMember_Call) Run(run func(userID int, roomID int)) *Store_IsMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int))
	})
	return _c
}

func (_c *Store_IsMember_Call) Return(_a0 bool, _a1 error) *Store_IsMember_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_IsMember_Call) RunAndReturn(run func(int, int) (bool, error)) *Store_IsMember_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveMember provides a mock function with given fields: userID, roomID
func (_m *Store) RemoveMember(userID int, roomID int) (types.Membership, error) {
	ret := _m.Called(userID, roomID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveMember")
	}

	var r0 types.Membership
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int) (types.Membership, error)); ok {
		return rf(userID, roomID)
	}
	if rf, ok := ret.Get(0).(func(int, int) types.Membership); ok {
		r0 = rf(userID, roomID)
	} else {
		r0 = ret.Get(0).(types.Membership)
	}

	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(userID, roomID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_RemoveMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveMember'
type Store_RemoveMember_Call struct {
	*mock.Call
}

// RemoveMember is a helper method to define mock.On call
//   - userID int
//   - roomID int
func (_e *Store_Expecter) RemoveMember(userID interface{}, roomID interface{}) *Store_RemoveMember_Call {
	return &Store_RemoveMember_Call{Call: _e.mock.On("RemoveMember", userID, roomID)}
}

func (_c *Store_RemoveMember_Call) Run(run func(userID int, roomID int)) *Store_RemoveMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int))
	})
	return _c
}

func (_c *Store_RemoveMember_Call) Return(_a0 types.Membership, _a1 error) *Store_RemoveMember_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_RemoveMember_Call) RunAndReturn(run func(int, int) (types.Membership, error)) *Store_RemoveMember_Call {
	_c.Call.Return(run)
	return _c
}

// RoomExists provides a mock function with given fields: roomID
func (_m *Store) RoomExists(roomID int) (bool, error) {
	ret := _m.Called(roomID)

	if len(ret) == 0 {
		panic("no return value specified for RoomExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (bool, error)); ok {
		return rf(roomID)
	}
	if rf, ok := ret.Get(0).(func(int) bool); ok {
		r0 = rf(roomID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(roomID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_RoomExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RoomExists'
type Store_RoomExists_Call struct {
	*mock.Call
}

// RoomExists is a helper method to define mock.On call
//   - roomID int
func (_e *Store_Expecter) RoomExists(roomID interface{}) *Store_RoomExists_Call {
	return &Store_RoomExists_Call{Call: _e.mock.On("RoomExists", roomID)}
}

func (_c *Store_RoomExists_Call) Run(run func(roomID int)) *Store_RoomExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *Store_RoomExists_Call) Return(_a0 bool, _a1 error) *Store_RoomExists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_RoomExists_Call) RunAndReturn(run func(int) (bool, error)) *Store_RoomExists_Call {
	_c.Call.Return(run)
	return _c
}

// NewStore creates a new instance of Store. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *Store {
	mock := &Store{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
