name: ci
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    paths: ['**/*.go', 'go.mod', 'go.sum', 'main.go', 'internal/**', 'db/**', 'sql/**', 'docker-compose.yaml', '.github/workflows/ci.yml']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.25'
      - run: go build ./...
      - run: go vet ./...
      - run: go test ./... -coverprofile=coverage.out
      - run: go tool cover -func=coverage.out
  auth-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: auth-service
    ## only run job on changes in auth dir
    paths: ['auth-service/**', '.github/workflows/ci.yml']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.25'
      - run: go build ./...
      - run: go vet ./...
      - run: go test ./... -coverprofile=coverage.out
      - run: go tool cover -func=coverage.out
  frontend-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    ## only run job on changes in frontend dir
    paths: ['frontend/**', '.github/workflows/ci.yml'] 
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - run: npm ci ## light, ci-specific npm install 
      - run: npm run lint
      - run: npx vitest run
      - run: npm run build
